
version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartstudy
      POSTGRES_USER: smartstudy_user
      POSTGRES_PASSWORD: smartstudy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartstudy_user -d smartstudy"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://smartstudy_user:smartstudy_password@db:5432/smartstudy
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY:-your-dev-secret-key-change-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
      - ALLOWED_HOSTS=["http://localhost:3000", "http://127.0.0.1:3000"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Database migrations
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://smartstudy_user:smartstudy_password@db:5432/smartstudy
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: alembic upgrade head
    restart: "no"

volumes:
  postgres_data:
  redis_data: